const UPDATE_LOCALE = 'UPDATE_LOCALE';
const UPDATE_PUNCTUAL = 'UPDATE_PUNCTUAL';
const UPDATE_RECURRENT = 'UPDATE_RECURRENT';
const UPDATE_DATE_TYPE = 'UPDATE_DATE_TYPE';
const UPDATE_CURRENCY = 'UPDATE_CURRENCY';

export {
  UPDATE_LOCALE,
  UPDATE_PUNCTUAL,
  UPDATE_RECURRENT,
  UPDATE_DATE_TYPE,
  UPDATE_CURRENCY,
};
