const UPDATE_LIST_RECURRENTS = 'UPDATE_LIST_RECURRENTS';
const UPDATE_COMPUTED_LIST_RECURRENTS = 'UPDATE_COMPUTED_LIST_RECURRENTS';

export {
  UPDATE_LIST_RECURRENTS,
  UPDATE_COMPUTED_LIST_RECURRENTS,
};
